---

sudo: true
services:
  - docker

before_install:
  - .travis/init-pyenv

script:
  - .travis/run-pyenv 'invoke travis'
  - .travis/run-pyenv 'invoke travis -s debian'
  - .travis/run-pyenv 'invoke travis -s squash_bug_hardcoded_pyenv_root'

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 2.7
