---

sudo: true
services:
  - docker

before_install:
  - .travis/init

script:
  - invoke travis
  - invoke travis -s debian
  - invoke travis -s squash_bug_hardcoded_pyenv_root

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 2.7
