---

sudo: true
services:
  - docker

before_install:
  - .travis/init

script:
  - . .jenkins-venv/bin/activate
  - invoke travis
  - invoke travis -s debian

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 2.7
