---

sudo: true
services:
  - docker

install:
  - .travis/init-pyenv

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 2.7
      cache: pip
      env: INVOKE_TASK='travis'
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 2.7
      cache: pip
      env: INVOKE_TASK='-s debian'
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 2.7
      cache: pip
      env: INVOKE_TASK='-s squash_bug_hardcoded_pyenv_root'

script:
  - .travis/run-pyenv invoke travis ${INVOKE_TASK}
